 version: 0.2
 
 env:
	   variables:
     CODEARTIFACT_AUTH_TOKEN: ''
     CODEARTIFACT_DOMAIN_OWNER: ''
     SONAR_LOGIN: ''
     SONAR_URL: ''
     SONAR_PROJECT_KEY: ''
 
 phases:
   install:
     runtime-versions:
       python: 3.10
     commands:
       - PIPELINE_NAME=$(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2)
       - echo "Pipeline Name: ${PIPELINE_NAME}"
       - BRANCH_NAME=$(aws codepipeline get-pipeline --name ${PIPELINE_NAME} --query "pipeline.stages[?name=='Source'].actions[0].configuration.BranchName" --output text)
       - echo "Branch Name: ${BRANCH_NAME}"
       - apt-get update > /dev/null 2>&1
       - apt-get install -y jq wget tar unzip > /dev/null 2>&1
       - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
       - unzip ./sonar-scanner-cli-6.2.1.4610-linux-x64.zip > /dev/null 2>&1
       - export PATH=$PATH:$(pwd)/sonar-scanner-6.2.1.4610-linux-x64/bin
 
   pre_build:
     on-failure: CONTINUE
     commands:
       - pip install coverage pytest
       - echo Fetching AWS CodeArtifact auth token...
       - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nda --domain-owner ${CODEARTIFACT_DOMAIN_OWNER} --region us-east-1 --query authorizationToken --output text`
 
   build:
     on-failure: CONTINUE
     commands:
       - ls -a
       - coverage run -m pytest && coverage xml --rcfile=.coveragerc
       - echo starting sonarqube static code analysis scan......
       - sonar-scanner -Dsonar.login=${SONAR_LOGIN} -Dsonar.host.url=${SONAR_URL} -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.sources=. -Dsonar.branch.name=$BRANCH_NAME -Dsonar.log.level=WARN
       - sleep 5
       - curl --location --user "${SONAR_LOGIN}:" "${SONAR_URL}/api/qualitygates/project_status?projectKey=${SONAR_PROJECT_KEY}&branch=$BRANCH_NAME" > result.json
       - echo "Retrieved SonarQube results:"
       - cat result.json
 
   post_build:
     commands:
       - echo sonarqube static code analysis complete