version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    on-failure: ABORT
    commands:
      - pip install --upgrade pip
      - pip install setuptools wheel twine build
      - pip install keyrings.alt
      - pip install -e '.[test]'
      - coverage run -m pytest && coverage report -m
      - |
        if [ -n "$PYPI_USER" ]; then
          echo "building project ...."
          python -m build
          # set repository to testpypi if env variable TEST_PYPI is set
          if [ -n "$PYPI_PASSWORD" ]; then
            echo "Pushing to PyPI"
            twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD
          elif [ -n "$TESTPYPI_PASSWORD" ]; then
            echo "Pushing to Test PyPI"
            twine upload dist/* -u $PYPI_USER -p $TESTPYPI_PASSWORD --repository-url https://test.pypi.org/legacy/        
          else
            echo "PYPI_PASSWORD not set"
            exit 1
          fi
        else
          echo "SKIPPING PUSH TO PYPI"
        fi
      - |
        if [ -n "$GITHUB_REPO" ]; then 
          echo "Setting up SSH key"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr "\t" "\n" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git remote set-url --push origin $GITHUB_REPO
          ssh -i ~/.ssh/id_rsa -T git@github.com
          echo "Extract the version number"
          initFilePath="NDATools/__init__.py"
          versionPattern="__version__ = '([0-9]+\.[0-9]+\.[0-9]+)'"
          initFileContent=$(cat "$initFilePath")
          git push origin
          if [ "$ENV" = "prod" ]; then
            versionNumber=$(echo "$initFileContent" | grep -Po "$versionPattern" | cut -d"'" -f2)
            if [ -n "$versionNumber" ]; then
              echo "Tagging version: $versionNumber"
              gitTag="$versionNumber"
              git tag "$gitTag"
              git push --tags
            else
              echo "Version number not found in __init__.py"
              exit 1
            fi 
          fi
        else
          echo "SKIPPING PUSH TO GITHUB"
        fi
  post_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - dist/*
